In [1]:
import numpy as np
import sys
import copy
import PySimpleGUI as sg

In [13]:
draw_interface()

Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION  5
ITERATION  6
ITERATION  7
Solutia a convers
Error = 6.435832792106959e-08
Primele 5 elemente din solutie:
[0.92665931 1.07952258 0.96608179 1.00273696 1.07624929]
Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION  5
ITERATION  6
ITERATION  7
Solutia a convers
Error = 4.82739543920499e-09
Primele 5 elemente din solutie:
[0.32758145 0.31777739 0.35655422 0.32661426 0.34972154]
Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION  5
ITERATION  6
ITERATION  7
ITERATION  8
ITERATION  9
ITERATION  10
Solutia a convers
Error = 7.02241717058631e-08
Primele 5 elemente din solutie:
[0.43456003 0.89654776 1.19295649 1.43894348 2.01796307]
Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION 

In [12]:
def draw_interface():
    global l, window, optimized_flag
    layout = [[sg.Button("TEST CASE 1")],
              [sg.Text(size=(100, 1), key="1")],
              
              [sg.Button("TEST CASE 2")],
              [sg.Text(size=(100, 1), key="2")],

              [sg.Button("TEST CASE 3")],
              [sg.Text(size=(100, 1), key="3")],

              [sg.Button("TEST CASE 4")],
              [sg.Text(size=(100, 1), key="4")],
              
              [sg.Button("TEST CASE 5")],
              [sg.Text(size=(100, 1), key="5")],

              [sg.Button("EXIT")]
             ]
    window = sg.Window("Calcul numeric - Laborator 4", layout)

    while True:
        event, values = window.read()

        if event == "EXIT":
            break
        elif event == "TEST CASE 1":
            window["1"].update(solve(1))
        elif event == "TEST CASE 2":
            window["2"].update(solve(2))
        elif event == "TEST CASE 3":
            window["3"].update(solve(3))
        elif event == "TEST CASE 4":
            window["4"].update(solve(4))
        elif event == "TEST CASE 5":
            window["5"].update(solve(5))

    window.close()

In [11]:
for i in range(1, 6):
    print('TEST CASE ', i)
    solve(i)

TEST CASE  1
Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION  5
ITERATION  6
ITERATION  7
Solutia a convers
Error = 6.435832792106959e-08
Primele 5 elemente din solutie:
[0.92665931 1.07952258 0.96608179 1.00273696 1.07624929]
TEST CASE  2
Citesc datele...
Am terminat citirea, incep sa rezolv
ITERATION  1
ITERATION  2
ITERATION  3
ITERATION  4
ITERATION  5
ITERATION  6
ITERATION  7


KeyboardInterrupt: 

In [5]:
epsilon = 10 ** (-8)

def solve(test_case):
    global abc
    
    print('Citesc datele...')
    (a,b,c,f,n,p,q) = read_data("./a" + str(test_case) + ".txt", "./f" + str(test_case) + ".txt")
    print('Am terminat citirea, incep sa rezolv')
    if validate_data(a) == -1:
        print('Eroare: determinant = 0')
        sys.exit()
    abc = a
    abc = np.append(abc, b)
    abc = np.append(abc, c)

    solution = getSolutionGaussSeidel(n, f, p, q, 20)
    
    print('Error = ' + str(get_average_error(abc, n, p, q, f, solution)))
    
    print('Primele 5 elemente din solutie:')
    print(solution[0:5])
    
    return solution[0:5]
    

In [6]:
def get_average_error(abc, n, p, q, f, solution):
    error = 0
    for i in range(0, n):
        value = 0
        if p + i <= n-1:
            value += matrix_to_array(n,p,q,i,p+i) * solution[p+i]
        if i >= q:
            value += matrix_to_array(n,p,q,i,i-q) * solution[i-q]
        value += matrix_to_array(n,p,q,i,i) * solution[i]
        error += abs(f[i] - value) * abs(f[i] - value)
    return error

In [7]:
def getSolutionGaussSeidel(n, f, p, q, number_iterations):
    global epsilon, abc
    
    x_prev = np.array([])
    for i in range(0, n):
        x_prev = np.append(x_prev, 0)
                
    for j in range(1, number_iterations):
        print('ITERATION ', j)
        x_current = np.array([])
        
        for i in range(0, n):
            suma1 = 0
            suma2 = 0
#             for t in range(0, i):
            if p + i <= n-1:
                suma1 = matrix_to_array(n,p,q,i,p+i) * x_prev[p+i]
#                 suma1 += (matrix_to_array(n, p, q, i, t) * x_current[t])
#             for t in range(i+1, n):
#                 suma2 += (matrix_to_array(n, p, q, i, t) * x_prev[t])
            if i >= q:
                suma2 = matrix_to_array(n,p,q,i,i-q) * x_current[i-q]

            final_value = (f[i] - suma1 - suma2) / matrix_to_array(n, p, q, i, i)
            x_current = np.append(x_current, final_value)
            
            
        sol_diff = 0
        for i in range(0, n):
            sol_diff += abs(x_prev[i] - x_current[i]) * abs(x_prev[i] - x_current[i])
        if sol_diff < epsilon:
            print('Solutia a convers')
            return x_current
        x_prev = copy.deepcopy(x_current)
        
    print('Divergenta!')
    return x_current

In [8]:
def read_data(file_name1, file_name2):
    file_read = open(file_name1, "r")
    a = np.array([])
    b = np.array([])
    c = np.array([])
    f = np.array([])
    n = int(file_read.readline())
    p = int(file_read.readline())
    q = int(file_read.readline())
    file_read.readline()
    for i in range(0, n):
        a = np.append(a, float(file_read.readline()[0:-1]))
    file_read.readline()
    for i in range(0, n-p):
        b = np.append(b, float(file_read.readline()[0:-1]))
    file_read.readline()
    for i in range(0, n-q):
        c = np.append(c, float(file_read.readline()[0:-1]))


        
    file_read2 = open(file_name2, "r")
    file_read2.readline()
    file_read2.readline()
    for i in range(0, n):
        f = np.append(f, float(file_read2.readline()[0:-1]))
    
    return (a,b,c,f,n,p,q)

In [9]:
def validate_data(a):
    for i in range(0, len(a)):
        if a[i] == 0:
            return -1
    return 1

In [10]:
def matrix_to_array(n, p, q, i, j):
    global abc
    if i != j and i+p != j and j+q != i:
        return 0
    if i == j:
        return abc[i]
    elif i < j:
        return abc[n + i]
    else:
        return abc[n + (n-p) + j]